# Generated by Django 3.2.3 on 2021-08-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210802_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
    ]
