# Generated by Django 3.2.3 on 2021-06-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mathamatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic1', models.CharField(max_length=100)),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('link3', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Maths',
        ),
    ]
