# Generated by Django 3.2.3 on 2021-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edify', '0002_auto_20210614_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic1', models.CharField(max_length=100)),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('link3', models.URLField()),
            ],
        ),
    ]
