# Generated by Django 3.2.3 on 2021-06-15 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edify', '0003_physics'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='channel1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='channel2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='channel3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
