# Generated by Django 3.2.3 on 2021-06-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edify', '0004_auto_20210615_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic1', models.CharField(max_length=100)),
                ('channel1', models.CharField(max_length=100)),
                ('link1', models.URLField()),
                ('channel2', models.CharField(max_length=100)),
                ('link2', models.URLField()),
                ('channel3', models.CharField(max_length=100)),
                ('link3', models.URLField()),
            ],
        ),
    ]
