# Generated by Django 3.2.3 on 2021-07-29 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edify', '0007_auto_20210729_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathamatics',
            name='link1',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
