# Generated by Django 3.2.3 on 2021-08-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edify', '0010_auto_20210807_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=models.TextField(),
        ),
    ]
